// Brand assets from one source of truth, without any font on the viewer's side.
//
// The ぱ of the mark and the ぱちぱち / 日文打字練習 of the social card are turned into SVG paths
// with fontkit (Noto Sans CJK JP Bold, SIL OFL), so the SVGs render identically everywhere; the
// PNGs are rasterised with resvg's WASM build. Pure JS, no native tooling.
//
// Usage: node scripts/brand.mjs
// Needs .cache/fonts/NotoSansCJKjp-Bold.otf (git-ignored). Get it once with
//   curl -L -o .cache/fonts/NotoSansCJKjp-Bold.otf \
//     https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Bold.otf
//
// Writes: static/icon.svg, src/lib/assets/favicon.svg, src/lib/assets/logo-glyph.ts,
//         static/icon-192.png, static/icon-512.png, static/apple-touch-icon.png, static/og.png
import { initWasm, Resvg } from '@resvg/resvg-wasm';
import * as fontkit from 'fontkit';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const FONT = '.cache/fonts/NotoSansCJKjp-Bold.otf';
if (!existsSync(FONT)) {
	console.error(`missing ${FONT} — see the header of this script for the download command`);
	process.exit(1);
}
const font = fontkit.openSync(FONT);
const require = createRequire(import.meta.url);
await initWasm(readFileSync(require.resolve('@resvg/resvg-wasm/index_bg.wasm')));

// Design tokens (MASTER.md). The SVG files are fixed-colour; Logo.svelte uses the CSS variables.
const ACCENT = '#0D9488';
const PLINTH = '#0A6B62';
const ON_ACCENT = '#FFFFFF';
const BG = '#FAFAFA';
const FG = '#18181B';
const MUTED = '#6B6B74';

/**
 * A text run as one SVG path `d`, laid out by the font (kerning included), at `size` px with
 * the pen starting at (x, baseline). Font units are y-up; the transform flips them.
 */
function textPath(text, size, x, baseline) {
	const scale = size / font.unitsPerEm;
	const run = font.layout(text);
	let pen = x;
	let d = '';
	run.glyphs.forEach((glyph, i) => {
		const pos = run.positions[i];
		const gx = pen + pos.xOffset * scale;
		const gy = baseline - pos.yOffset * scale;
		d += glyph.path.transform(scale, 0, 0, -scale, gx, gy).toSVG();
		pen += pos.xAdvance * scale;
	});
	return { d, width: pen - x };
}

function centredTextPath(text, size, cx, baseline) {
	const probe = textPath(text, size, 0, 0);
	return textPath(text, size, cx - probe.width / 2, baseline);
}

/** The keycap mark in a 64×64 box; `glyph` is the ぱ path (or the text fallback for Svelte). */
function markSvg({ glyph, cap = ACCENT, plinth = PLINTH, ink = ON_ACCENT }) {
	return `<rect x="4" y="10" width="56" height="52" rx="14" fill="${plinth}"/>
	<rect x="4" y="4" width="56" height="52" rx="14" fill="${cap}"/>
	<path d="${glyph}" fill="${ink}"/>
	<g stroke="${ink}" stroke-width="3.2" stroke-linecap="round" fill="none" opacity="0.92">
		<path d="M47 20 L52 15"/>
		<path d="M50 27 L57 25"/>
		<path d="M43 15 L43 8"/>
	</g>`;
}

// ぱ at 32px, centred on x=29 with its baseline at y=43 — the same placement as the text version.
const pa = centredTextPath('ぱ', 32, 29, 43).d;

const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
	${markSvg({ glyph: pa })}
</svg>
`;
writeFileSync('static/icon.svg', iconSvg);
writeFileSync('src/lib/assets/favicon.svg', iconSvg);
writeFileSync(
	'src/lib/assets/logo-glyph.ts',
	`// Generated by scripts/brand.mjs — the ぱ of the mark as a path (Noto Sans CJK JP Bold, OFL),
// so the logo does not depend on the viewer's fonts. Do not edit by hand.
export const LOGO_GLYPH_PA = ${JSON.stringify(pa)};
`
);

function png(svg, width) {
	return new Resvg(svg, { fitTo: { mode: 'width', value: width } }).render().asPng();
}

writeFileSync('static/icon-192.png', png(iconSvg, 192));
writeFileSync('static/icon-512.png', png(iconSvg, 512));

// Apple wants an opaque square: the mark on the page background with a little air around it.
const appleSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="180" height="180">
	<rect width="64" height="64" fill="${BG}"/>
	<g transform="translate(4 4) scale(0.875)">${markSvg({ glyph: pa })}</g>
</svg>`;
writeFileSync('static/apple-touch-icon.png', png(appleSvg, 180));

// Social card 1200×630: mark, wordmark, tagline. Nothing else — MASTER.md「lots of whitespace」.
const word = textPath('ぱちぱち', 150, 0, 0);
const tag = textPath('日文打字練習', 54, 0, 0);
const markSize = 220;
const gap = 48;
const totalW = markSize + gap + word.width;
const left = (1200 - totalW) / 2;
const top = 190;
const ogSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">
	<rect width="1200" height="630" fill="${BG}"/>
	<g transform="translate(${left} ${top}) scale(${markSize / 64})">${markSvg({ glyph: pa })}</g>
	<path d="${textPath('ぱちぱち', 150, left + markSize + gap, top + 158).d}" fill="${FG}"/>
	<path d="${textPath('日文打字練習', 54, left + markSize + gap + 6, top + 158 + 92).d}" fill="${MUTED}"/>
	<rect x="${left}" y="${top + markSize + 96}" width="${totalW}" height="4" rx="2" fill="${ACCENT}"/>
</svg>`;
void tag;
writeFileSync('static/og.png', png(ogSvg, 1200));

console.log(
	'brand assets written: icon.svg, favicon.svg, logo-glyph.ts, icon-192/512.png, apple-touch-icon.png, og.png'
);
