import { sql } from 'drizzle-orm';
import {
	index,
	integer,
	primaryKey,
	real,
	sqliteTable,
	text,
	uniqueIndex
} from 'drizzle-orm/sqlite-core';
import { user } from './auth-schema.ts';

// Better Auth tables (user / session / account / verification) are generated by
// `pnpm --filter web auth:schema` into ./auth-schema.ts (spec §4). Never hand-edit them.
export { account, session, user, verification } from './auth-schema.ts';

/** One practice run or timed race (spec §4). */
export const runs = sqliteTable(
	'runs',
	{
		id: text('id').primaryKey(), // ulid
		userId: text('user_id').references(() => user.id, { onDelete: 'set null' }), // null → anonymous
		mode: text('mode').notNull(), // 'lesson:hira-a' | 'timed:allhira:60' | ...
		kpm: integer('kpm').notNull(),
		accuracy: real('accuracy').notNull(), // 0..1
		score: integer('score').notNull(),
		correctKeys: integer('correct_keys').notNull(),
		wrongKeys: integer('wrong_keys').notNull(),
		durationMs: integer('duration_ms').notNull(),
		// Longest streak of accepted keys, recomputed from the log server-side (M4-3).
		// Nullable: runs recorded before the column existed have no combo.
		maxCombo: integer('max_combo'),
		week: text('week').notNull(), // 'YYYY-Www' in Asia/Taipei
		flagged: integer('flagged').notNull().default(0), // 1 → anticheat suspect
		// Why an otherwise honest run stays off the leaderboard; null → ranked. 'accuracy' = below
		// the 90 % floor (DECISIONS「分數規則定案」). Unlike `flagged`, the reason is shown to the user.
		unrankedReason: text('unranked_reason'),
		createdAt: integer('created_at').notNull() // epoch ms
	},
	(t) => [
		index('runs_lb').on(t.mode, t.week, sql`${t.score} DESC`),
		index('runs_user').on(t.userId, sql`${t.createdAt} DESC`)
	]
);

/** Per-user, per-kana attempt stats for the weak-spot heatmap / SRS (spec §4, §7.3). */
export const kanaStats = sqliteTable(
	'kana_stats',
	{
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		kana: text('kana').notNull(), // one unit: 'か' 'きゃ' 'っか'
		attempts: integer('attempts').notNull().default(0),
		errors: integer('errors').notNull().default(0),
		lastSeenAt: integer('last_seen_at').notNull()
	},
	(t) => [primaryKey({ columns: [t.userId, t.kana] })]
);

/**
 * A shared timeline for a video: **no lyric text ever lands here**.
 *
 * Only the video id, the number of lines, a hex SHA-256 per line text (`lineHashes`) and the
 * `start` seconds are stored, so a user who pasted the same reading can be offered the timings
 * without the server ever holding or distributing the words (DECISIONS「歌曲功能定案」item 3).
 */
export const songTimings = sqliteTable(
	'song_timings',
	{
		id: text('id').primaryKey(), // ulid
		videoId: text('video_id').notNull(),
		lineCount: integer('line_count').notNull(),
		lineHashes: text('line_hashes').notNull(), // JSON: hex SHA-256 per line, in order
		starts: text('starts').notNull(), // JSON: number[] (seconds), same length as lineHashes
		createdBy: text('created_by').references(() => user.id, { onDelete: 'set null' }),
		useCount: integer('use_count').notNull().default(0),
		createdAt: integer('created_at').notNull() // epoch ms
	},
	(t) => [index('song_timings_video').on(t.videoId)]
);

/**
 * A rights holder's notice about a public content (著作權法 §90-4～§90-12 / notice-and-takedown).
 * `contentId` points at the `contents` row (a user-provided song since M4-1c); it is kept as a
 * null reference when the row is gone so the report itself stays on record.
 */
export const takedownRequests = sqliteTable('takedown_requests', {
	id: text('id').primaryKey(), // ulid
	contentId: text('content_id').references(() => contents.id, { onDelete: 'set null' }),
	videoId: text('video_id').notNull().default(''),
	reporterContact: text('reporter_contact').notNull(), // e-mail or any reply address they give
	claim: text('claim').notNull(),
	status: text('status').notNull().default('open'), // 'open' | 'removed' | 'rejected'
	adminNote: text('admin_note'),
	createdAt: integer('created_at').notNull(), // epoch ms
	resolvedAt: integer('resolved_at')
});

/** Repeat-infringer record: three removals and the user may no longer publish. */
export const userStrikes = sqliteTable('user_strikes', {
	userId: text('user_id')
		.primaryKey()
		.references(() => user.id, { onDelete: 'cascade' }),
	strikes: integer('strikes').notNull().default(0),
	suspendedAt: integer('suspended_at') // epoch ms of the third strike
});

/** In-app notice for a user (no e-mail is ever sent from the Worker); shown on /me. */
export const notices = sqliteTable(
	'notices',
	{
		id: text('id').primaryKey(), // ulid
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		kind: text('kind').notNull(), // 'song_removed' | 'suspended'
		message: text('message').notNull(),
		createdAt: integer('created_at').notNull(), // epoch ms
		readAt: integer('read_at')
	},
	(t) => [index('notices_user').on(t.userId, sql`${t.createdAt} DESC`)]
);

/**
 * One piece of Japanese content (M4-1): a song, an anime line set, a news piece, a novel
 * excerpt, a JLPT drill or free text. Everything the platform practises on goes through this
 * one model — **the repo itself ships no content**. Two kinds of row live here:
 *
 * - **platform content** (`ownerId = null`): imported by an admin through `/admin/contents`,
 *   listed on `/contents` once `status = 'published'`. The rights columns are not decoration:
 *   `rightsStatus` must be `'cleared'` before it may be published (ROADMAP M4-1「rightsStatus
 *   不明者不得發布」), and `sourceType` / `sourceUrl` / `sourceName` / `license` record where
 *   the text came from so that claim can be checked later.
 * - **user-provided content** (`ownerId` set, `sourceType = 'user_provided'`; since M4-1c the
 *   former `songs` table): the user's own pasted reading of lyrics, **private by default**
 *   (`status = 'draft'` → only the owner reads it), never in the public `/contents` list. The
 *   owner may set it `'published'` after ticking the rights declaration, which is what
 *   `publicConsentAt` records; `'removed'` is the notice-and-takedown outcome, kept with
 *   `removedReason` so the handling stays on record. Anonymous visitors keep their library in
 *   localStorage and never reach this table.
 */
export const contents = sqliteTable(
	'contents',
	{
		id: text('id').primaryKey(), // ulid
		type: text('type').notNull(), // 'song' | 'anime' | 'news' | 'novel' | 'jlpt' | 'free'
		title: text('title').notNull(),
		description: text('description').notNull().default(''),
		videoId: text('video_id'), // 11-char YouTube id when the content is timed to a video
		jlptLevel: text('jlpt_level').notNull().default('unknown'), // 'N5'..'N1' | 'unknown'
		difficulty: text('difficulty').notNull().default('normal'), // easy | normal | hard | expert
		status: text('status').notNull().default('draft'), // 'draft' | 'published' | 'removed'
		sourceType: text('source_type').notNull().default('original'), // original | licensed | public_domain | user_provided | other
		sourceUrl: text('source_url').notNull().default(''),
		sourceName: text('source_name').notNull().default(''),
		license: text('license').notNull().default(''),
		rightsStatus: text('rights_status').notNull().default('unknown'), // 'cleared' | 'unknown'
		createdBy: text('created_by').references(() => user.id, { onDelete: 'set null' }),
		// User-provided content only (null → platform content). The row goes with the account.
		ownerId: text('owner_id').references(() => user.id, { onDelete: 'cascade' }),
		publicConsentAt: integer('public_consent_at'), // epoch ms of the owner's rights declaration
		removedReason: text('removed_reason'), // set with status = 'removed'
		createdAt: integer('created_at').notNull(), // epoch ms
		updatedAt: integer('updated_at').notNull() // epoch ms
	},
	(t) => [
		index('contents_list').on(t.status, t.type, sql`${t.updatedAt} DESC`),
		index('contents_jlpt').on(t.status, t.jlptLevel),
		index('contents_owner').on(t.ownerId, sql`${t.updatedAt} DESC`)
	]
);

/**
 * One typing question of a content, in reading order.
 *
 * `originalText` is what the source says (kanji included), `kanaText` is what the engine types
 * and `romajiText` is the reading aid; the last two are produced in the browser by the import
 * pipeline (`lib/ja/`) and corrected by the admin in the Line Editor. `startTime` / `endTime`
 * (seconds into `contents.videoId`) turn the content into a sync run; without them it is a
 * plain sequential run.
 */
export const contentLines = sqliteTable(
	'content_lines',
	{
		id: text('id').primaryKey(), // ulid
		contentId: text('content_id')
			.notNull()
			.references(() => contents.id, { onDelete: 'cascade' }),
		order: integer('order').notNull(), // 0-based position
		startTime: real('start_time'), // seconds into the video
		endTime: real('end_time'), // seconds into the video
		originalText: text('original_text').notNull(),
		kanaText: text('kana_text').notNull(),
		romajiText: text('romaji_text').notNull().default(''),
		metadata: text('metadata') // JSON, free-form per-line notes
	},
	(t) => [uniqueIndex('content_lines_order').on(t.contentId, t.order)]
);

/**
 * Daily counters behind the admin analytics (M4-4「分析事件」): how often a published content was
 * viewed, started and completed. One row per (Taipei day, content, kind) with a count — no user
 * id, no session id, nothing to tie an event to a person. The core metric is
 * completes / starts per content.
 */
export const contentEventsDaily = sqliteTable(
	'content_events_daily',
	{
		day: text('day').notNull(), // 'YYYY-MM-DD' in Asia/Taipei
		contentId: text('content_id')
			.notNull()
			.references(() => contents.id, { onDelete: 'cascade' }),
		kind: text('kind').notNull(), // 'view' | 'start' | 'complete'
		count: integer('count').notNull().default(0)
	},
	(t) => [primaryKey({ columns: [t.day, t.contentId, t.kind] })]
);

export type Run = typeof runs.$inferSelect;
export type NewRun = typeof runs.$inferInsert;
export type KanaStat = typeof kanaStats.$inferSelect;
export type SongTimingRow = typeof songTimings.$inferSelect;
export type NewSongTimingRow = typeof songTimings.$inferInsert;
export type TakedownRow = typeof takedownRequests.$inferSelect;
export type NewTakedownRow = typeof takedownRequests.$inferInsert;
export type UserStrikeRow = typeof userStrikes.$inferSelect;
export type NoticeRow = typeof notices.$inferSelect;
export type NewNoticeRow = typeof notices.$inferInsert;
export type ContentRow = typeof contents.$inferSelect;
export type NewContentRow = typeof contents.$inferInsert;
export type ContentLineRow = typeof contentLines.$inferSelect;
export type NewContentLineRow = typeof contentLines.$inferInsert;
export type ContentEventRow = typeof contentEventsDaily.$inferSelect;
